---
cluster:
  max-partitions: 16
cache:
  db-cache: false
  db-cache-clean-wait: 20
  db-cache-size: 0.5
  db-cache-time: 180000
storage:
  backend: hbase
  hbase:
    table: cross-sell-example
  hostname: localhost
  port: 2181
ioformat:
    filter-partitioned-vertices: true