---
application:
  back-off-time: 1500
  retries: 5
  batch-size: 100
  zookeeper:
    timeout: 10000
cluster:
  partition: true
  max-partitions: 4
ids:
  flush: false
graph:
  set-vertex-id: true
cache:
  db-cache: true
  db-cache-clean-wait: 20
  db-cache-size: 0.5
  db-cache-time: 180000
storage:
  backend: hbase
  hbase:
    table: cross-sell-example
    short-cf-names: false
  hostname: 127.0.0.1
  port: 2181
ioformat:
    filter-partitioned-vertices: true
    vertex-query: v.has("productId")