---
cluster:
  max-partitions: 16
cache:
  db-cache: true
  db-cache-clean-wait: 20
  db-cache-size: 0.5
  db-cache-time: 180000
storage:
  backend: hbase
  hbase:
    table: tinkerpop-examples
  hostname: localhost
  port: 2181